// This file contains static paths for all brand images to ensure accuracy

class BrandImages {
  static const Map<String, String> imagePaths = {
    // Lowercase filenames
    'Abarth': 'assets/images/brandimages/abarth.png',
    'Acura': 'assets/images/brandimages/Accura.png',
    'Audi': 'assets/images/brandimages/audi.png',
    'Baojun': 'assets/images/brandimages/baojun.png',
    'Bentley': 'assets/images/brandimages/bentley.png',
    'Brilliance': 'assets/images/brandimages/brilliance.png',
    'Bugatti': 'assets/images/brandimages/bugatti.png',
    'Buick': 'assets/images/brandimages/buick.png',
    'Changan': 'assets/images/brandimages/changan.png',
    'Chery': 'assets/images/brandimages/chery.png',
    'Dongfeng': 'assets/images/brandimages/dongfeng.png',
    'FAW': 'assets/images/brandimages/faw.png',
    'GAC Motors': 'assets/images/brandimages/gac_motors.png',
    'Geely': 'assets/images/brandimages/geely.png',
    'Greatwall': 'assets/images/brandimages/great_wall_motors.png',
    'Haval': 'assets/images/brandimages/haval.png',
    'JAC Motors': 'assets/images/brandimages/jac motors.png',
    'Kia': 'assets/images/brandimages/KIA.PNG',
    'MG Motor': 'assets/images/brandimages/mg.png',
    'NIO': 'assets/images/brandimages/nio.png',
    'Nissan': 'assets/images/brandimages/nissan.png',
    'Opel': 'assets/images/brandimages/opel.png',
    'Pagani': 'assets/images/brandimages/pagani.png',
    'Peugeot': 'assets/images/brandimages/peugeot.png',
    'Polestar': 'assets/images/brandimages/Polester.png',
    'Porsche': 'assets/images/brandimages/porsche.png',
    'Ram': 'assets/images/brandimages/ram.png',
    'Renault': 'assets/images/brandimages/renault.png',
    'Rolls-Royce': 'assets/images/brandimages/rolls royce..png',
    'Saab': 'assets/images/brandimages/saab.png',
    'Seat': 'assets/images/brandimages/seat.png',
    'Skoda': 'assets/images/brandimages/skoda.png',
    'Smart': 'assets/images/brandimages/smart.png',
    'SsangYong': 'assets/images/brandimages/ssangyong.png',
    'Subaru': 'assets/images/brandimages/subaru.png',
    'Suzuki': 'assets/images/brandimages/suzuki.png',
    'Tata Motors': 'assets/images/brandimages/tata motors.png',
    'Tesla': 'assets/images/brandimages/tesla.png',
    'Toyota': 'assets/images/brandimages/toyota.png',
    'Vauxhall': 'assets/images/brandimages/vauxhall.png',
    'Volkswagen': 'assets/images/brandimages/volkswagen.png',
    'Volvo': 'assets/images/brandimages/volvo.png',
    'Wiesmann': 'assets/images/brandimages/wiesmann.png',
    'Wuling': 'assets/images/brandimages/wuling.png',
    'Zotye': 'assets/images/brandimages/zotye.png',

    // Uppercase filenames
    'BMW': 'assets/images/brandimages/BMW.png',
    'BYD': 'assets/images/brandimages/BYD.PNG',
    'Cadillac': 'assets/images/brandimages/Cadillac.PNG',
    'Chevrolet': 'assets/images/brandimages/Chevrolet.PNG',
    'Chrysler': 'assets/images/brandimages/Chrysler.PNG',
    'Citroën': 'assets/images/brandimages/Citroën.PNG',
    'Cupra': 'assets/images/brandimages/Cupra.PNG',
    'DFM': 'assets/images/brandimages/DFM.PNG',
    'DS Automobiles': 'assets/images/brandimages/DS Automobiles.PNG',
    'Dacia': 'assets/images/brandimages/Dacia.PNG',
    'Daewoo': 'assets/images/brandimages/Daewoo.PNG',
    'Daihatsu': 'assets/images/brandimages/Daihatsu.PNG',
    'Datsun': 'assets/images/brandimages/Datsun.PNG',
    'Dodge': 'assets/images/brandimages/Dodge.PNG',
    'Ferrari': 'assets/images/brandimages/Ferrari.PNG',
    'Fiat': 'assets/images/brandimages/Fiat.PNG',
    'Ford': 'assets/images/brandimages/Ford.PNG',
    'GMC': 'assets/images/brandimages/GMC.PNG',
    'Genesis': 'assets/images/brandimages/Genesis.PNG',
    'Honda': 'assets/images/brandimages/Honda.PNG',
    'Hyundai': 'assets/images/brandimages/Hyundai.PNG',
    'Infiniti': 'assets/images/brandimages/Infiniti.PNG',
    'Isuzu': 'assets/images/brandimages/Isuzu.PNG',
    'Jaguar': 'assets/images/brandimages/Jaguar.PNG',
    'Jeep': 'assets/images/brandimages/Jeep.PNG',
    'Koenigsegg': 'assets/images/brandimages/Koenigsegg.PNG',
    'Lamborghini': 'assets/images/brandimages/Lamborghini.PNG',
    'Lancia': 'assets/images/brandimages/Lancia.PNG',
    'Land Rover': 'assets/images/brandimages/Land Rover.PNG',
    'Lexus': 'assets/images/brandimages/Lexus.PNG',
    'Lincoln': 'assets/images/brandimages/Lincoln.PNG',
    'Lotus': 'assets/images/brandimages/Lotus.PNG',
    'MG': 'assets/images/brandimages/MG (Morris Garages).PNG',
    'Mahindra': 'assets/images/brandimages/Mahindra.PNG',
    'Maserati': 'assets/images/brandimages/Maserati.PNG',
    'Mazda': 'assets/images/brandimages/Mazda.PNG',
    'McLaren': 'assets/images/brandimages/McLaren.PNG',
    'Mercedes-Benz': 'assets/images/brandimages/Mercedes-Benz.PNG',
    'Mini': 'assets/images/brandimages/Mini.PNG',
    'Mitsubishi': 'assets/images/brandimages/Mitsubishi.PNG',

    // Brands with special characters or spaces in filenames
    'Alfa Romeo': 'assets/images/brandimages/Alfa-Romeo.png',
    'Aston Martin': 'assets/images/brandimages/Aston-Martin.png',
  };

  static String? getBrandImagePath(String brandName) {
    return imagePaths[brandName];
  }
}
